// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDto1Lj5JHFjbzZamHp81f7uz_yfFG6lNs',
    appId: '1:679497502497:web:c739c22c2aab6a37f67860',
    messagingSenderId: '679497502497',
    projectId: 'expand-fa561',
    authDomain: 'expand-fa561.firebaseapp.com',
    storageBucket: 'expand-fa561.firebasestorage.app',
    measurementId: 'G-BBD6FHJF84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGEIPGLDcW6L_ECkD1F3bFvGPwG94_aYM',
    appId: '1:679497502497:android:b9d93ce0dd600a1df67860',
    messagingSenderId: '679497502497',
    projectId: 'expand-fa561',
    storageBucket: 'expand-fa561.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACQ_o0gpxRFU6FaB2QmMMAaTaw2FgITg8',
    appId: '1:679497502497:ios:bc9857958e804e34f67860',
    messagingSenderId: '679497502497',
    projectId: 'expand-fa561',
    storageBucket: 'expand-fa561.firebasestorage.app',
    iosBundleId: 'com.example.expand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACQ_o0gpxRFU6FaB2QmMMAaTaw2FgITg8',
    appId: '1:679497502497:ios:bc9857958e804e34f67860',
    messagingSenderId: '679497502497',
    projectId: 'expand-fa561',
    storageBucket: 'expand-fa561.firebasestorage.app',
    iosBundleId: 'com.example.expand',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDto1Lj5JHFjbzZamHp81f7uz_yfFG6lNs',
    appId: '1:679497502497:web:eeb6f31fcb22f69ef67860',
    messagingSenderId: '679497502497',
    projectId: 'expand-fa561',
    authDomain: 'expand-fa561.firebaseapp.com',
    storageBucket: 'expand-fa561.firebasestorage.app',
    measurementId: 'G-7MDL9JBYNE',
  );
}
