class ProductData {
  List<Map<String, dynamic>> clothingProducts = [
    {
      'name': 'Classic White T-Shirt',
      'price': 19.99,
      'size': ['S', 'M', 'L', 'XL'],
      'color': 'White',
      'material': '100% Cotton',
    },
    {
      'name': 'Black Denim Jeans',
      'price': 49.99,
      'size': ['28', '30', '32', '34'],
      'color': 'Black',
      'material': 'Denim',
    },
    {
      'name': 'Striped Polo Shirt',
      'price': 29.99,
      'size': ['S', 'M', 'L'],
      'color': 'Navy/White',
      'material': 'Cotton/Polyester',
    },
    {
      'name': 'Hooded Sweatshirt',
      'price': 39.99,
      'size': ['M', 'L', 'XL'],
      'color': 'Gray',
      'material': 'Fleece',
    },
    {
      'name': 'Cargo Shorts',
      'price': 34.99,
      'size': ['30', '32', '34'],
      'color': 'Khaki',
      'material': 'Cotton Twill',
    },
    {
      'name': 'V-Neck Sweater',
      'price': 45.99,
      'size': ['S', 'M', 'L'],
      'color': 'Burgundy',
      'material': 'Merino Wool',
    },
    {
      'name': 'Athletic Leggings',
      'price': 27.99,
      'size': ['XS', 'S', 'M'],
      'color': 'Black',
      'material': 'Spandex/Nylon',
    },
    {
      'name': 'Flannel Shirt',
      'price': 32.99,
      'size': ['S', 'M', 'L', 'XL'],
      'color': 'Red/Black',
      'material': 'Brushed Cotton',
    },
    {
      'name': 'Bomber Jacket',
      'price': 89.99,
      'size': ['M', 'L', 'XL'],
      'color': 'Olive Green',
      'material': 'Polyester',
    },
    {
      'name': 'Chino Pants',
      'price': 42.99,
      'size': ['30', '32', '34', '36'],
      'color': 'Beige',
      'material': 'Cotton',
    },
    {
      'name': 'Tank Top',
      'price': 14.99,
      'size': ['S', 'M', 'L'],
      'color': 'Heather Gray',
      'material': 'Cotton/Lycra',
    },
    {
      'name': 'Winter Parka',
      'price': 129.99,
      'size': ['S', 'M', 'L'],
      'color': 'Navy',
      'material': 'Nylon/Insulated',
    },
    {
      'name': 'Oxford Shirt',
      'price': 37.99,
      'size': ['S', 'M', 'L'],
      'color': 'Light Blue',
      'material': 'Cotton Oxford',
    },
    {
      'name': 'Yoga Pants',
      'price': 29.99,
      'size': ['XS', 'S', 'M', 'L'],
      'color': 'Dark Purple',
      'material': 'Polyester/Spandex',
    },
    {
      'name': 'Leather Jacket',
      'price': 199.99,
      'size': ['S', 'M', 'L'],
      'color': 'Black',
      'material': 'Genuine Leather',
    },
    {
      'name': 'Canvas Sneakers',
      'price': 49.99,
      'size': ['7', '8', '9', '10'],
      'color': 'White',
      'material': 'Canvas/Rubber',
    },
    {
      'name': 'Cashmere Scarf',
      'price': 59.99,
      'size': ['One Size'],
      'color': 'Camel',
      'material': 'Cashmere',
    },
    {
      'name': 'Swim Trunks',
      'price': 24.99,
      'size': ['S', 'M', 'L'],
      'color': 'Navy/White',
      'material': 'Quick-Dry Polyester',
    },
    {
      'name': 'Wool Coat',
      'price': 149.99,
      'size': ['S', 'M', 'L'],
      'color': 'Charcoal',
      'material': 'Wool Blend',
    },
    {
      'name': 'Graphic Tee',
      'price': 22.99,
      'size': ['S', 'M', 'L', 'XL'],
      'color': 'Black',
      'material': 'Cotton',
    },
    {
      'name': 'Corduroy Pants',
      'price': 44.99,
      'size': ['30', '32', '34'],
      'color': 'Brown',
      'material': 'Cotton Corduroy',
    },
    {
      'name': 'Puffer Vest',
      'price': 64.99,
      'size': ['S', 'M', 'L'],
      'color': 'Black',
      'material': 'Nylon/Down',
    },
    {
      'name': 'Silk Blouse',
      'price': 59.99,
      'size': ['S', 'M', 'L'],
      'color': 'Ivory',
      'material': 'Silk',
    },
    {
      'name': 'Cable Knit Sweater',
      'price': 52.99,
      'size': ['S', 'M', 'L'],
      'color': 'Cream',
      'material': 'Wool/Acrylic',
    },
    {
      'name': 'Jogger Pants',
      'price': 39.99,
      'size': ['S', 'M', 'L'],
      'color': 'Dark Gray',
      'material': 'Cotton/Spandex',
    },
    {
      'name': 'Denim Jacket',
      'price': 69.99,
      'size': ['S', 'M', 'L'],
      'color': 'Light Wash',
      'material': 'Denim',
    },
    {
      'name': 'Linen Shirt',
      'price': 47.99,
      'size': ['S', 'M', 'L'],
      'color': 'White',
      'material': 'Linen',
    },
    {
      'name': 'Fleece Pullover',
      'price': 54.99,
      'size': ['M', 'L', 'XL'],
      'color': 'Navy',
      'material': 'Polyester Fleece',
    },
    {
      'name': 'Wool Socks (3-pack)',
      'price': 19.99,
      'size': ['One Size'],
      'color': 'Assorted',
      'material': 'Merino Wool',
    },
    {
      'name': 'Rain Jacket',
      'price': 79.99,
      'size': ['S', 'M', 'L'],
      'color': 'Yellow',
      'material': 'Waterproof Nylon',
    },
  ];
}
